version: "3.8"

services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-runner:latest
    container_name: github-runner
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/runner-work:/home/runner/_work   # workflow data on host
      - /home/ubuntu/runner-tmp:/tmp                  # temporary downloads on host

volumes:
  runner-data:
